# CQ: Is this product still covered by the legal guarantee?
SELECT ?product ?endTime ?valid
WHERE {
    ?info a/rdfs:subClassOf* dpp-info:LegalGuarantee ;
        dpp-prov:isAbout ?product .

    OPTIONAL {
        ?info dpp-prov:invalidAtTimeStamp ?endTime
        BIND(?endTime > NOW() AS ?valid)
    }
}