# CQ: Information was provided by a value chain actor for a specifc product in China. Another value chain actor wants to view the provided DPP infomation, but not in Chinese but in English.
SELECT ?info ?info_label ?info_comment ?class_label ?class_comment
WHERE {
    ?info a/rdfs:subClassOf* dpp-dpp-info:DPPInformation ;
        a ?class .
    OPTIONAL {
        ?info rdfs:label ?info_label .
        FILTER(lang(?info_label) = "en")
    }
    OPTIONAL {
        ?info rdfs:comment ?info_comment .
        FILTER(lang(?info_comment) = "en")
    }
    OPTIONAL {
        ?class rdfs:label ?class_label .
        FILTER(lang(?class_label) = "en")
    }
    OPTIONAL {
        ?class rdfs:comment ?class_comment .
        FILTER(lang(?class_comment) = "en")
    }
}