# CQ: What is the meaning of a specific information within a DPP?
SELECT ?dpp ?info ?class ?label ?description
WHERE {
    ?dpp a/rdfs:subClassOf* dpp-odp:DPP ;
        dpp-info:containsInformation ?info .
    ?info a/rdfs:subClassOf* ?class .
    
    ?class rdfs:label ?label ;
        rdfs:comment ?description .
}