# CQ: Who/what actor is responsible for what set of information in a DPP?
SELECT ?dpp ?responsibleActor ?info
WHERE {
    ?dpp a/rdfs:subClassOf* dpp-odp:DPP ;
        dpp-odp:containsInformation ?info .
    ?info a/rdfs:subClassOf* dpp-info:DPPInformation ;
        dpp-prov:responsibleActor ?responsibleActor . 
}