# CQ: What kind of additional information is provided (in terms of data source type)?
#     Where to find this additional information?
SELECT ?product ?info ?document
WHERE {
    ?dpp a/rdfs:subClassOf* dpp-odp:DPP ;
        dpp-odp:describes ?product ;
        dpp-odp:containsInformation ?info .
    ?info dpp-info:externalDocument ?document .
}