# CQ: What is the meaning of a specific information within a DPP?
SELECT ?info ?class ?document
WHERE {
    ?info a/rdfs:subClassOf* dpp-info:DPPInformation .
        a ?class .
    ?info dpp-info:externalDocument ?document .
}