# CQ: How can the product be disassembled?
SELECT ?product ?info ?document
WHERE {
    ?product a/rdfs:subClassOf* dpp-odp:Product .
    ?info dpp-info:isAbout ?product ;
        dpp-odp:containsInformation ?info . 
    ?info a/rdfs:subClassOf* dpp-info:DisassemblyInformation ;
        dpp-info:dissasemblyInstructionsDocument ?document .
}