# CQ: What is the quality of the contained material?
SELECT ?product ?material ?quality ?value ?unit
WHERE {
    ?product a/rdfs:subClassOf* dpp-odp:Product .
    ?info a dpp-info:isAbout ?product .
        dpp-odp:hasPart* ?material .
    ?material a dpp-odp:Material .

    ?info a/rdfs:subClassOf* dpp-info:ProductQuality ;
        dpp-info:quality ?quality .

    ?quality dpp-info:value ?value ;
        dpp-info:unit ?unit .
}