# CQ: What information does the seller (or another value chain actor) provide to the consumers on how to repair the product?
SELECT ?product ?instructions
WHERE {
    ?product a/rdfs:subClassOf* dpp-odp:Product .
    ?info dpp-info:isAbout ?product ;
        a/rdfs:subClassOf* dpp-info:RepairInstructions ;
        dpp-prov:responsibleActor ?actor ;
        dpp-info:repairInstructionsDocument ?instructions .   
}