# CQ: When was this piece of information/statement recorded/observed, added to the DPP, changed, or when does it cease to be valid?
SELECT ?dpp ?info ?creationTime ?invalidationTime
WHERE {
    ?dpp a/rdfs:subClassOf* dpp-odp:DPP ;
        dpp-odp:containsInformation ?info .
    ?info dpp-prov:creationTimeStamp ?creationTime .
    OPTIONAL { ?info dpp-prov:invalidationTimeStamp ?invalidationTime }
}