# CQ: What is the most recent version of the information in the DPP?
SELECT ?dpp ?info ?creationTime ?invalidationTime
WHERE {
    ?dpp a/rdfs:subClassOf* dpp-odp:DPP ;
        dpp-odp:containsInformation/dpp-info:supersededBy* ?info .
    ?info dpp-prov:creationTimeStamp ?creationTime .
    OPTIONAL { ?info dpp-prov:invalidationTimeStamp ?invalidationTime }
    FILTER NOT EXISTS { ?info dpp-info:supersededBy ?newInfo }
}